"""Approved 16x16 MCP activity UI, derived from the reference mockups.

GENERATED by scripts/generate_activity_ui_data.py from assets/ui/reference/.
Do not edit by hand: a test re-derives this file and fails if it drifts.

Layout (approved spec): rows 0-2 activity crown, 3-4 spacer, 5-9 identity
letters, 10 divider, 11-15 icons. Columns are 5 px per source; x=15 is spare.
All colours are RGB222-legal (channels in 0/85/170/255), which is a strict
subset of the RGB888 the Ditoo encoder already sends -- the palette is a design
constraint inherited with the artwork, never a device constraint.
"""
from __future__ import annotations

SIZE = 16
STATUSES = ('green', 'yellow', 'red', 'grey')

# source id -> leftmost x of its 5 px column
SLOTS = {'optiplex_lab': 0, 'optiplex_mcp': 5, 'wsl_mcp': 10}

# Pixels that never change: the sprite bodies, stems, ears and bones.
FIXED = (
    (181, (255, 255, 255)),
    (184, (255, 255, 255)),
    (187, (255, 255, 255)),
    (188, (170, 170, 170)),
    (189, (170, 170, 170)),
    (193, (255, 170, 170)),
    (198, (255, 255, 255)),
    (200, (255, 255, 255)),
    (202, (255, 255, 255)),
    (203, (255, 255, 255)),
    (204, (255, 255, 170)),
    (205, (170, 170, 170)),
    (206, (170, 170, 170)),
    (215, (255, 255, 255)),
    (219, (170, 170, 170)),
    (221, (255, 255, 170)),
    (222, (85, 85, 85)),
    (226, (85, 85, 85)),
    (230, (255, 255, 255)),
    (231, (255, 255, 255)),
    (232, (255, 255, 255)),
    (234, (255, 255, 255)),
    (235, (85, 85, 85)),
    (236, (255, 255, 255)),
    (237, (85, 85, 85)),
    (238, (85, 85, 85)),
    (242, (255, 255, 255)),
    (246, (170, 170, 170)),
    (247, (255, 255, 255)),
    (248, (170, 170, 170)),
    (249, (85, 85, 85)),
    (251, (170, 170, 170)),
    (252, (85, 85, 85)),
)

# Pixels that carry status, and the colour each role takes per status.
ROLE_COLORS = {
    'accent': {'green': (0, 255, 0), 'yellow': (255, 255, 0), 'red': (255, 0, 0), 'grey': (85, 85, 85)},
    'cap_base': {'green': (0, 255, 0), 'yellow': (255, 255, 0), 'red': (255, 0, 85), 'grey': (170, 170, 170)},
    'cap_dark': {'green': (0, 170, 0), 'yellow': (170, 170, 0), 'red': (170, 0, 0), 'grey': (85, 85, 85)},
    'cap_light': {'green': (85, 255, 85), 'yellow': (255, 255, 85), 'red': (255, 85, 85), 'grey': (170, 170, 170)},
}

ROLE_PIXELS = {
    'accent': (81, 86, 87, 90, 94, 97, 101, 104, 106, 110, 113, 117, 120, 122, 124, 126, 129, 133, 136, 138, 139, 141, 142, 145, 146, 147, 150, 151, 154, 158, 214, 216, 218, 220),
    'cap_base': (178, 194, 195, 209, 210, 211, 212),
    'cap_dark': (177, 192),
    'cap_light': (179, 196, 208),
}

# Activity crown, as (dx, dy, rgb) offsets from the active column's left edge.
CROWN = ((0, 0, (0, 170, 255)), (4, 0, (0, 170, 255)), (1, 1, (85, 170, 255)), (3, 1, (85, 170, 255)), (2, 2, (0, 255, 255)))

# During activity every status pixel in that column takes this one colour.
OVERRIDE_RGB = (85, 170, 255)
