"""Approved 16x16 MCP activity UI, derived from the reference mockups.

GENERATED by scripts/generate_activity_ui_data.py from assets/ui/reference/.
Do not edit by hand: a test re-derives this file and fails if it drifts.

Layout: rows 0-2 activity crown, 3-4 spacer, 5-9 icons, 10 divider, 11-15
identity letters. Columns are 5 px per source; x=15 is spare. The approved
mockups place letters above icons; the two blocks are swapped here at the
operator's request, as an explicit transform (see generate_activity_ui_data.py).
All colours are RGB222-legal (channels in 0/85/170/255), which is a strict
subset of the RGB888 the Ditoo encoder already sends -- the palette is a design
constraint inherited with the artwork, never a device constraint.
"""
from __future__ import annotations

SIZE = 16
STATUSES = ('green', 'yellow', 'red', 'grey')

# source id -> leftmost x of its 5 px column
SLOTS = {'optiplex_lab': 0, 'optiplex_mcp': 5, 'wsl_mcp': 10}

# Pixels that never change: the sprite bodies, stems, ears and bones.
FIXED = (
    (85, (255, 255, 255)),
    (88, (255, 255, 255)),
    (91, (255, 255, 255)),
    (92, (170, 170, 170)),
    (93, (170, 170, 170)),
    (97, (255, 170, 170)),
    (102, (255, 255, 255)),
    (104, (255, 255, 255)),
    (106, (255, 255, 255)),
    (107, (255, 255, 255)),
    (108, (255, 255, 170)),
    (109, (170, 170, 170)),
    (110, (170, 170, 170)),
    (119, (255, 255, 255)),
    (123, (170, 170, 170)),
    (125, (255, 255, 170)),
    (126, (85, 85, 85)),
    (130, (85, 85, 85)),
    (134, (255, 255, 255)),
    (135, (255, 255, 255)),
    (136, (255, 255, 255)),
    (138, (255, 255, 255)),
    (139, (85, 85, 85)),
    (140, (255, 255, 255)),
    (141, (85, 85, 85)),
    (142, (85, 85, 85)),
    (146, (255, 255, 255)),
    (150, (170, 170, 170)),
    (151, (255, 255, 255)),
    (152, (170, 170, 170)),
    (153, (85, 85, 85)),
    (155, (170, 170, 170)),
    (156, (85, 85, 85)),
)

# Pixels that carry status, and the colour each role takes per status.
ROLE_COLORS = {
    'accent': {'green': (0, 255, 0), 'yellow': (255, 255, 0), 'red': (255, 0, 0), 'grey': (85, 85, 85)},
    'cap_base': {'green': (0, 255, 0), 'yellow': (255, 255, 0), 'red': (255, 0, 85), 'grey': (170, 170, 170)},
    'cap_dark': {'green': (0, 170, 0), 'yellow': (170, 170, 0), 'red': (170, 0, 0), 'grey': (85, 85, 85)},
    'cap_light': {'green': (85, 255, 85), 'yellow': (255, 255, 85), 'red': (255, 85, 85), 'grey': (170, 170, 170)},
}

ROLE_PIXELS = {
    'accent': (118, 120, 122, 124, 177, 182, 183, 186, 190, 193, 197, 200, 202, 206, 209, 213, 216, 218, 220, 222, 225, 229, 232, 234, 235, 237, 238, 241, 242, 243, 246, 247, 250, 254),
    'cap_base': (82, 98, 99, 113, 114, 115, 116),
    'cap_dark': (81, 96),
    'cap_light': (83, 100, 112),
}

# Activity crown, as (dx, dy, rgb) offsets from the active column's left edge.
CROWN = ((0, 0, (0, 170, 255)), (4, 0, (0, 170, 255)), (1, 1, (85, 170, 255)), (3, 1, (85, 170, 255)), (2, 2, (0, 255, 255)))

# During activity every status pixel in that column takes this one colour.
OVERRIDE_RGB = (85, 170, 255)
